name: PythonFSDAM
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - openmm
  - pip
  - python
  - mdtraj
  - scipy
  - pandas
  - parmed
  - MDAnalysis>=1.1.1
  - pip:
    - 'git+https://github.com/MauriceKarrenbrock/FSDAMGromacs.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonAuxiliaryFunctions'
    - 'git+https://github.com/MauriceKarrenbrock/PythonPDBStructures'
